####
# 라이브러리와 버전 관리
####
[versions]
androidx-compose-bom = "2023.05.01"

androidx-core-ktx = "1.10.0"
androidx-lifecycle-runtime-ktx = "2.6.2"
androidx-activity-compose = "1.7.2"
androidx-navigation-compose = "2.5.3"
okhttp3 = "4.10.0"
retrofit2 = "2.9.0"
retrofit2-converter-gson = "2.6.0"
retrofit2-jackson = "2.3.0"
okhttp3-logging-interceptor = "4.9.3"
dagger-hilt = "2.42"
dagger-hilt-compiler = "2.42"

test-junit = "4.13.2"

android-test-androidx-ext-junit = "1.1.5"
android-test-androidx-espresso-core = "3.5.1"
android-test-androidx-compose-bom = "2023.03.00"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preivew = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2-converter-gson" }
retrofit2-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit2-jackson" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3-logging-interceptor" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt-compiler" }


test-junit = { module = "junit:junit", version.ref = "test-junit" }
android-test-androidx-ext-junit = { module = "androidx.test.ext:junit", version.ref = "android-test-androidx-ext-junit" }
android-test-androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "android-test-androidx-espresso-core" }
android-test-androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "android-test-androidx-compose-bom" }

debug-androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
debug-androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }